### ISSUE TITLE
What's the license if any?

### ISSUE THREAD

**Issue by samrocketman** [mozmeao/jenkins-pipeline#9]
I would like to use files from this repository in my own project: https://github.com/samrocketman/jervis

Jervis is licensed under Apache Standard License 2.0.

Please let me know as you have a lot of nice scripts I would like to use.  I would add a reference link back to this repository as to where I got them.

**Comment by glogiotatidis** [comment]
Hi @samrocketman. Under discussion in #10 but it'll definitely be something that allows sharing and collaboration. We're welcoming PRs too!

**Comment by samrocketman** [comment]
Thanks!
